### ISSUE TITLE
Only check http / https links

### ISSUE THREAD

**Issue by ScholliYT** [ScholliYT/Broken-Links-Crawler-Action#4]

**Comment by aceberle** [comment]
Does this mean that you only want to crawl links that begin with "https://", or does it mean that you want to automatically convert all links to use "https://" even if "http://" is specified on the site being crawled?  Thanks!

**Comment by ScholliYT** [comment]
No, this is meant more like: "dont check links like tel:+49123123123 or email:somone@example.com" 
So the protocol should be some sort of http

**Comment by aceberle** [comment]
Oh, I get it now, thanks for explaining.

With the #13 PR, I am introducing a config flag called `resolve_before_filtering` which when enabled would cause the code to fully resolve the link URL before applying the filtering.  This may be a solution for this issue because you can enable that setting and then set `include_url_prefix` to `'http://,https://'` and then the crawler will only pick up http/https links.
